# Generated by Django 5.1.3 on 2024-12-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membershipModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('User_name', models.CharField(max_length=255)),
                ('Email_address', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'membership_tbl',
            },
        ),
    ]
