# Generated by Django 5.1.3 on 2024-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmodel',
            name='Password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membershipmodel',
            name='User_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='membershipmodel',
            table='Membership_tbl',
        ),
    ]
