# Generated by Django 5.1.3 on 2024-12-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_membershipmodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmodel',
            name='Password',
            field=models.CharField(max_length=512),
        ),
    ]
