# Generated by Django 5.1.3 on 2024-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_membershipmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmodel',
            name='User_name',
            field=models.CharField(max_length=255),
        ),
    ]
