# Generated by Django 5.1.3 on 2024-12-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_membershipmodel_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmodel',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
