# Generated by Django 5.1.3 on 2024-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_membershipmodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membershipmodel',
            name='Email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipmodel',
            name='User_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
